name: flutter_project_template
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  colorize: ^3.0.0
  connectivity_plus: ^6.1.5
  fimber: ^0.7.0
  fluttertoast: ^8.2.12
  get_it: ^8.2.0
  flutter_svg: ^2.2.0
  google_fonts: ^6.3.1
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  http: ^1.5.0
  equatable: ^2.0.7
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  floor: ^1.5.0
  flutter_secure_storage: ^9.2.4
  go_router: ^16.2.1
  intl: ^0.20.2
  device_preview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  floor_generator: ^1.5.0
  build_runner: ^2.4.1
  flutter_launcher_icons: ^0.14.4 
  flutter_native_splash: ^2.4.6


#* Add your flutter launcher icon here
#? RUN COMMAND: dart run flutter_launcher_icons:generate
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

#* Add your flutter native splash icons here
#? RUN COMMAND: dart run flutter_native_splash:create
flutter_native_splash:
  color: "#51B848"
  image: assets/images/logo_large.png
  android_gravity: center
  ios_content_mode: scaleAspectFit
  fullscreen: true
  android: true
  ios: true
  color_dark: "#51B848"
  image_dark: assets/images/logo_large.png
  android_12:
    image: assets/images/app_icon.png
    icon_background_color: "#51B848"
    fullscreen: true
    image_dark: assets/images/app_icon.png
    icon_background_color_dark: "#51B848"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf

